#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/thymus.
#
# SPDX-License-Identifier: Apache-2.0
#

# Deployment for mailslurper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thymus.fullname" . }}-mailslurper
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "thymus.name" . }}-mailslurper
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.thymus.policyCatalogue.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thymus.name" . }}-mailslurper
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thymus.name" . }}-mailslurper
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.mailslurper.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.mailslurper.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      containers:
        - name: "{{ .Chart.Name }}-mailslurper"
          image: "{{ .Values.mailslurper.image.registry }}/{{ .Values.mailslurper.image.repository }}:{{ .Values.mailslurper.image.tag }}"
          imagePullPolicy: {{ .Values.mailslurper.image.pullPolicy }}
          ports:
            - name: ui
              containerPort: 4436
              protocol: TCP
            - name: api
              containerPort: 4437
              protocol: TCP
            - name: smtp
              containerPort: 1025
              protocol: TCP
---
# Service for exposing mailslurper
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thymus.fullname" . }}-mailslurper
  namespace: {{ .Release.Namespace }}
  {{- if .Values.mailslurper.service.annotations }}
  annotations:
{{ .Values.mailslurper.service.annotations | toYaml | trim | indent 4 }}
  {{- end}}
spec:
  selector:
    app.kubernetes.io/name: {{ include "thymus.name" . }}-mailslurper
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.mailslurper.service.uiPort }}
      targetPort: ui
    - name: api
      protocol: TCP
      port: {{ .Values.mailslurper.service.apiPort }}
      targetPort: api
    - name: smtp
      protocol: TCP
      port: {{ .Values.mailslurper.service.smtpPort }}
      targetPort: smtp
