#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/thymus.
#
# SPDX-License-Identifier: Apache-2.0
#

# Create demo users
{{- if .Values.thymus.users.enabled }}
{{- range $index, $value := .Values.thymus.users.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "user-credentials-{{ $index }}"
data:
  data.json: |
    {
     "traits": {
        "email": "{{ $value.email }}"
      },
      "credentials": {
        "password": {
          "config": {
            "password": "{{ $value.password }}"
          }
        }
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "create-user-{{ $index }}"
spec:
  backoffLimit: 5
  template:
    spec:
      volumes:
        - name: user-credentials-volume
          configMap:
            name: "user-credentials-{{ $index }}"
      containers:
        - name: add-user
          image: pnnlmiscscripts/curl-jq
          {{- $files := $.Files }}
          command:
            - "sh"
            - "-c"
            - {{ $files.Get "scripts/create-user.sh" | quote | indent 14 }}
          env:
            - name: MAILSLURPER_ADDRESS
              value: "{{ include "thymus.fullname" $ }}-mailslurper:{{ $.Values.mailslurper.service.apiPort }}"
            - name: KRATOS_ADMIN_SERVICE_ADDRESS
              value: {{ printf "%s-kratos-admin:%d" (include "thymus.fullname" $) (int $.Values.kratos.service.admin.port) }}
            - name: KRATOS_PUBLIC_SERVICE_ADDRESS
              value: {{ printf "%s-kratos-public:%d" (include "thymus.fullname" $) (int $.Values.kratos.service.public.port) }}
          volumeMounts:
            - name: user-credentials-volume
              mountPath: /user-credentials
      restartPolicy: OnFailure
{{- end }}
{{- end }}
