#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/thymus.
#
# SPDX-License-Identifier: Apache-2.0
#

# Service for exposing the policy catalogue
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thymus.fullname" . }}-policy-catalogue
  namespace: {{ .Release.Namespace }}
  {{- if .Values.thymus.policyCatalogue.service.annotations }}
  annotations:
{{ .Values.thymus.policyCatalogue.service.annotations | toYaml | trim | indent 4 }}
  {{- end}}
spec:
  selector:
    app.kubernetes.io/name: {{ include "thymus.name" . }}-policy-catalogue
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.thymus.policyCatalogue.service.port }}
      targetPort: http
