#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/thymus.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Publish Services
on:
  push:
    tags:
      - "services-v[0-9]+.[0-9]+.[0-9]+"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: carbynestack/thymus
jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      WORKING_DIRECTORY: ${{ github.workspace }}/src/github.com/${{ github.repository }}/services
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Retrieve license obligation resources
        run: |
          cd 3RD-PARTY-LICENSES
          find . -maxdepth 1 -type d -not -path . | zip -r@ 3rd-party-copyrights
          find . -iname origin.src | \
          awk '{ \
          split($0,b,"/"); \
          system("xargs < " $0 " curl --create-dirs -Lo ./sources/" b[2] ".zip " $2)}' && \
          find -regex './sources$' | awk '{system("zip -jr ./3rd-party-sources.zip " $0)}'
          mkdir -p ../license-obligations && mv `find . -regex "^./3rd-party-.*.zip$"` ../license-obligations/
      - name: Update Release with license obligations resources
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.WORKING_DIRECTORY }}/license-obligations/*
          artifactErrorsFailBuild: true
          makeLatest: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=services-v(\d+.\d+.\d+),group=1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/services/go.mod
          cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/services/go.sum
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.7
      - name: Publish Docker Images
        run: |
          # Generate tags flag (Metadata action output is newline delimited entries like
          # 'ghcr.io/carbynestack/thymus:0.1.10' and we only need the part after the colon)
          readarray -t tags < <( echo "${{ steps.meta.outputs.tags }}" )
          for i in "${!tags[@]}"; do
            readarray -d ":" -t parts < <( echo "${tags[i]}" )
            tags[i]=$(echo "${parts[1]}" | tr -d '\n')
          done
          printf -v joined_tags "%s," "${tags[@]}"

          # Generate label flags
          readarray -t labels < <( echo "${{ steps.meta.outputs.labels }}" )
          printf -v label_flags -- "--image-label=%s " "${labels[@]}"

          # Publish using ko
          ko publish -B \
            --tags="${joined_tags%,}" \
            "${label_flags}" \
            github.com/carbynestack/thymus/services/cmd/catalogue
